### ISSUE TITLE
Better way to specify multiple query params

### ISSUE THREAD

**Issue by lispyclouds** [into-docker/unixsocket-http#17]
Currently `request` takes a map of str->str as `:query-params` and assumes the query param keys are unique, but we should be able to pass the same keys again with different values, for example here in [this](https://docs.podman.io/en/latest/_static/api.html#operation/ContainersStatsAllLibpod) api for Podman.

The [way](https://github.com/into-docker/unixsocket-http/blob/main/src/unixsocket_http/data.clj#L40) the url is built allows us the pass the params as `[[k1 v1] [k2 v2] [k1 v2]]` as discovered by accident by @leahneukirchen in https://github.com/lispyclouds/contajners/issues/8

I think a formal way of specify multi arg query params would be nice in this lib? I can work around this for now. What do you think @xsc?

**Comment by xsc** [comment]
I guess the most sensible thing to do is copying [clj-http's behaviour](https://github.com/dakrone/clj-http/tree/c11e191f0a8c170117bce37317f1b957e62e9985#query-string-parameters). This means:

* Allow arrays to be passed as values.
* By default, repeat the parameter for each value.
* Introduce `:multi-param-style` to change the behaviour.

We can start without the last bullet point, I'd say.

**Comment by leahneukirchen** [comment]
So quick, thanks a lot!

**Comment by xsc** [comment]
@leahneukirchen No worries.

Released as `1.0.12`.
