### ISSUE TITLE
Unix sockets don't work on Java 21+

### ISSUE THREAD

**Issue by lispyclouds** [into-docker/unixsocket-http#19]
When using via [contajners](https://github.com/lispyclouds/contajners), this is the error I'm seeing when trying to connect to Podman over a unix socket:

```
Execution error (SocketException) at org.newsclub.net.unix.NativeUnixSocket/setCreated (NativeUnixSocket.java:-2).
Cannot find method "setCreated" or field "created" in java.net.Socket. Unsupported JVM?
```

This is possibly from the junixsocket library. This works fine for HTTP connections. Possibly the dependency needs a upgrade?

**Comment by lispyclouds** [comment]
hey @xsc just a gentle nudge for the release when possible? will cut out a release for contajners too following that. Thanks again! 🙏🏽

**Comment by xsc** [comment]
@lispyclouds It took me a while to verify that GraalVM compatibility was still there. And then I had to handle the fact that my GPG keys had expired. But now version `1.0.13` is released. :)
