### ISSUE TITLE
HTTPS Support?

### ISSUE THREAD

**Issue by lispyclouds** [into-docker/unixsocket-http#3]
Since the primary aim of this is to enable communications with the docker daemon, if the daemon is made to listen on a TCP socket too, its generally HTTPS.
Would be nice to enable https support for this. I'll try to see if I can rasie a patch for this.

**Comment by xsc** [comment]
@lispyclouds I have implemented some kind of HTTPS support. Do you have a testcase in mind we could use to verify?

**Comment by lispyclouds** [comment]
Hey @xsc thanks a lot for this!

I have tried this with curl:
- Start a dind container with: `docker run --rm -it --name dind --privileged docker:dind`
- Exec into it with `docker exec -it dind sh`
- Install curl with `apk add curl`
- Then `curl -k --key /certs/client/key.pem --cert /certs/client/cert.pem https://localhost:2376/_ping` should give `OK`

By design the docker HTTP server needs the client to present a cert, can we do this here? We cant provide a cert and private key when making the client right?

**Comment by xsc** [comment]
We can pass a `:builder-fn` when creating the client, which then has access to the `OkHttpClient.Builder` and can adjust it in any way it wants (see [here](https://github.com/into-docker/unixsocket-http/blob/master/test/unixsocket_http/test/http_server.clj#L116-L119)), e.g.:

```clojure
(def certs
  (-> (HandshakeCertificates$Builder.)
      (.addTrustedCertificate ...)
      (.build)))

(uhttp/client
  "https://localhost:12345"
  {:builder-fn
   (fn [^okhttp3.OkHttpClient$Builder builder]
     (.sslSocketFactory builder
                        (.sslSocketFactory certs)
                        (.trustManager certs)))})
```

There's still a lot of legwork to do to actually get the `X509Certificate` to use with [`HandshakeCertificates`](https://square.github.io/okhttp/4.x/okhttp-tls/okhttp3.tls/-handshake-certificates/-builder/) but I feel like that's not necessarily in the scope of this library.

**Comment by lispyclouds** [comment]
Looks good to me, it would be helpful if this is documented and I can adapt the clj-docker-client and use this doc too.

**Comment by xsc** [comment]
@lispyclouds I added a section to the README:

![image](https://user-images.githubusercontent.com/198072/103459011-5a02a080-4d0c-11eb-8207-3d5bb8ed850c.png)

I've still not gotten around to creating a full example with Docker, though.
